# -*- coding: utf-8 -*-
"""ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSiYsDolE28ShCQ01Ez6iz7ormgvRJcL
"""

#Ejercicio 2: Análisis del Clima
 #Utilice el archivo clima.csv para analizar los datos climáticos:
 #. Cargue el dataset y conviértelo en un DataFrame.
 #. Calcule la temperatura promedio de cada ciudad.
 #. Determine el registro con la temperatura más alta y el más bajo en el dataset.
 #. Identifique qué ciudad tuvo la temperatura más alta y cuál la más baja en todo el dataset.
 #. Encuentre cuántos registros tienen una temperatura mayor a 30°C.
 #. Cuenta cuántos días en total hay registrados por cada ciudad.

#usar panda
import pandas as pd
#Leer df
df = pd.read_csv('clima.csv')
df.head()

# Calculo de temperatura promedio de cada ciudad
# Se agrupa el DataFrame por ciudad y se calcula la media de la columna 'Temperatura' para cada grupo.
temp_prom_ciudad = df.groupby('Ciudad')['Temperatura'].mean()

# Registro con la temperatura más alta y el más bajo
# Se utiliza idxmax() para encontrar el índice de la temperatura máxima y loc[] para obtener la fila completa.
reg_temp_max = df.loc[df['Temperatura'].idxmax()]
# Se utiliza idxmin() para encontrar el índice de la temperatura mínima y loc[] para obtener la fila completa.
reg_temp_min = df.loc[df['Temperatura'].idxmin()]

# Ciudad con la temperatura más alta y la más baja
# Se extrae el nombre de la ciudad del registro con la temperatura máxima.
ciudad_temp_max = reg_temp_max['Ciudad']
# Se extrae el nombre de la ciudad del registro con la temperatura mínima.
ciudad_temp_min = reg_temp_min['Ciudad']

# Registros con temperatura mayor a 30°C
# Se filtra el DataFrame para obtener las filas donde la temperatura es mayor a 30.
regs_mayor_30 = df[df['Temperatura'] > 30]
# Se calcula la cantidad de registros con temperatura mayor a 30 utilizando len().
cant_regs_mayor_30 = len(regs_mayor_30)

# Contar días registrados por cada ciudad
# Se agrupa el DataFrame por ciudad y se cuenta la cantidad de fechas únicas para cada ciudad.
dias_ciudad = df.groupby('Ciudad')['Fecha'].count()

# Mostrar resultados
# Se imprimen todos los resultados obtenidos.
print("Temperatura promedio por ciudad:\n", temp_prom_ciudad)
print("\nRegistro con temperatura máxima:\n", reg_temp_max)
print("\nRegistro con temperatura mínima:\n", reg_temp_min)
print("\nCiudad con temperatura máxima:", ciudad_temp_max)
print("\nCiudad con temperatura mínima:", ciudad_temp_min)
print("\nCantidad de registros con temperatura mayor a 30°C:", cant_regs_mayor_30)
print("\nDías registrados por cada ciudad:\n", dias_ciudad)