# -*- coding: utf-8 -*-
"""Ejercicio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbZp0Up08Zmn6wVYOZEH73FHlDlUk9eM
"""

# Ejercicio 1: Análisis de Ventas
# Utilice el archivo ventas.csv para responder lo siguiente:
 #. Cargue los datos en un DataFrame.
 #. Calcule la cantidad total de productos vendidos por categoría.
 #. Determine cuál es el producto con el mayor total de ventas.
 #. Encuentre el precio promedio de los productos vendidos.

import pandas as pd

df = pd.read_csv('./ventas.csv')
df.head()



# Calcular la cantidad total de productos vendidos por categoría
productos_por_categoria = df.groupby('Producto')['Cantidad'].sum()
print(productos_por_categoria)

# Determinar el producto con el mayor total de ventas
producto_mayor_venta = df.groupby('Producto')['Precio_Unitario'].sum().idxmax()
print(f"Producto con el mayor total de ventas: {producto_mayor_venta}")

# Encontrar el precio promedio de los productos vendidos
precio_promedio = df['Precio_Unitario'].mean()
print(f"Precio promedio de los productos vendidos:  {precio_promedio}")